# Site settings
title: 'Kris Lee | 专注移动互联，提供移动开发、培训与解决方案'
description: '专注移动互联，提供移动开发、培训与解决方案'
url: 'http://krislq.com'
baseurl: '/'
google_analytics: 'UA-86802058-1'
# disqus_shortname: 'your-disqus-name'
excerpt_separator: <!--more-->  # you can specify your own separator, of course.

author:
  name: 'Kris Lee'
  email: kris@krislq.com
  twitter_username: qianhen136
  facebook_username: krislqiang
  github_username:  krislq
  linkedin_username:  krislq

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
